title: Faversham Pub Reviews
tagline: Finding the best pubs in Faversham
description: >-
 Discover Faversham’s finest pubs with detailed reviews and traditional insights.
 Your definitive guide to exploring the best pubs in Faversham.

url: "https://faversham.pub"

github_username:  radams15


theme: jekyll-theme-yat

translate_langs: []

google_analytics: "G-6J2PBDGVBP"
enableDNT: "false"

defaults:
  home:
    heading: "Faversham Pub Reviews"
    subheading: "Exploring Faversham, one pub at a time"
    banner: "/assets/images/banner.small.jpg"

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
