title: faversham.pub
description: >-
  Exploring the pubs of Faversham

url: "https://faversham.pub"

github_username:  radams15


theme: jekyll-theme-yat

translate_langs: []

google_analytics: "G-6J2PBDGVBP"
enableDNT: "false"

defaults:
  home:
    heading: "Faversham.pub"
    subheading: "Exploring faversham, one pub at a time"
    banner: "/assets/images/banner.small.jpg"

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
