title: faversham.pub
description: >-
  Exploring the pubs of Faversham

url: "https://faversham.pub"

github_username:  radams15


theme: jekyll-theme-yat

translate_langs: []

defaults:
  home:
    heading: "Faversham.pub"
    subheading: "Exploring faversham, one pub at a time"
    banner: "/assets/images/banner.small.jpg"

plugins:
  - jekyll-feed
  - jekyll-sitemap
