title: faversham.pub
description: >-
  Exploring the pubs of Faversham

url: "https://faversham.pub"

github_username:  radams15


theme: jekyll-theme-yat
# remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-feed
  - jekyll-sitemap
